baseURL = '/'
locale = 'pt-br'
title = 'Guia Rápido para o Java'
theme = "nojs"
summaryLength = 70
# https://gitlab.com/andy.sb/nojs
paginate = 10

[params]
favicon_16 = "/assets/favicon.ico"

[caches]
[caches.images]
dir = ':cacheDir/images'

[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20
